# Site settings
title: Regis A. Ely
email: regisaely@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Professor of Economics at Federal University of Pelotas with research interests in applied economics, finance, banking, time series analysis and forecasting. Topics on my site include teaching materials, research articles, and softwares such as R, Python, LaTeX, Emacs and Github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://regisely.com" # the base hostname & protocol for your site
twitter_username: regisaely
github_username:  regisely
orcid_id: 0000-0002-2468-3761
google_scholar_id: yjbuYNEAAAAJ
githubdir: "regisely/regisely.github.io"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Adjunct Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: ""
google_site_verification: "S_qmlQRyXu4Qln3eDJ06JJrOuTzltYH1Yryjhj7HFcI"
bing_webmastertools_id: ""

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
