---
title: "Revisiting Reinhart and Rogoff, Ten Years Later"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
   rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })
author: "steve"
date: '2020-04-20'
excerpt: "Reinhart and Rogoff's paper may have had more immediate influence on economics than any other paper in history, but it's a showcase on how not to do research."
layout: post
categories:
  - R
  - Political Science
---


```{r setup, include=TRUE, cache=F}

x<-1:10
plot(x)

```

Texto

```{r fx, include=TRUE, cache=F}
library(tidyverse)
library(Quandl)
library(plotly)
Quandl.api_key("sdZ68BF3CzK2VneXxUgy")
currs <- tibble(
  code = c("DEXUSAL", "DEXBZUS", "DEXUSUK", "DEXCAUS", "DEXCHUS", "DEXDNUS",
           "DEXUSEU", "DEXHKUS", "DEXINUS", "DEXJPUS", "DEXMAUS", "DEXMXUS",
           "DEXTAUS", "DEXUSNZ", "DEXNOUS", "DEXSIUS", "DEXSFUS", "DEXKOUS",
           "DEXSLUS", "DEXSDUS", "DEXSZUS", "DEXTHUS"),
  currency = c("Australian Dollar (AUD)", "Brazilian Real (BRL)",
               "British Pound (GBP)", "Canadian Dollar (CAD)",
               "Chinese Yuan (CNY))", "Denish Krone (DKK)", "Euro (EUR)",
               "Hong Kong Dollar (HKD)", "Indian Rupee (INR)",
               "Japanese Yen (JPY)", "Malaysian Ringgit (MYR)",
               "Mexican Peso (MXN)", "New Taiwan Dollar (TWD)",
               "New Zealand Dollar (NZD)", "Norwegian Krone(NOK)",
               "Singapore Dollar (SGD)", "South African Rand(ZAR)",
               "South Korean Won (KRW)", "Sri Lankan Rupee(LKR)",
               "Swedish Krona (SEK)", "Swiss Franc (CHF)", "Thai Baht (THB)")
)

inverted <- c("DEXUSAL", "DEXUSUK", "DEXUSEU", "DEXUSNZ", "DEXVZUS")

codes <- paste0("FRED/", currs$code)
data_raw <- Quandl(codes, type = "raw", order = "asc", start_date = "2020-01-01")
colnames(data_raw) <- c("date", currs$code)

data <- data_raw %>%
  pivot_longer(-date, names_to = "code", values_to = "rate") %>%
  left_join(currs, by = "code") %>%
  mutate(rate = if_else(code %in% inverted, 1/rate, rate)) %>%
  drop_na()

p <- data %>%
  group_by(code) %>%
  mutate(cumrate = (rate / first(rate)) - 1) %>%
  ungroup() %>%
  ggplot(aes(x = date, y = cumrate, color = currency)) +
  geom_line() 
py <- plot_ly(username="r_user_guide", key="mw5isa4yqp")
py$ggplotly(p, dynamicTicks = TRUE)
```
