---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/OneDrive/resources/templates/latex/cv.tex
geometry: margin=1in

title: "CV"
author: Regis Augusto Ely

jobtitle: "Associate Professor, Federal University of Pelotas"
address: "Rua Gomes Carneiro nº 1 - 4º andar · Department of Economics · Pelotas RS, Brazil 96010-610"
fontawesome: yes
email: regisaely@gmail.com
# github: regisely
# twitter: regisaely
#osf: "Enter 5 digit osf string here"
#phone: "+353 1 408 4800"
web: regisely.com
updated: no

#keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment\break

***Federal University of Pelotas***

Associate Professor \hfill 2020-present

Adjunct Professor \hfill 2012-2020

Head of Department (Department of Economics/UFPel) \hfill 2022-2024

Postgraduate Coordinator (PPGOM/UFPel) \hfill 2019-2021

Head of Department (Department of Economics/UFPel) \hfill 2016-2018\break

***Catholic University of Pelotas***

Lecturer (MBE Controladoria e Finanças/UCPEL) \hfill 2017-2018\break

***Federal University of Rio Grande do Sul***

Lecturer (Department of Economics/UFRGS) \hfill  2011\break

***Caixa Econômica Federal***

Bank officer (Credit Management, FCVS and FIES) \hfill  2005-2008\break

# Education\break

*Getulio Vargas Foundation (EPPG/FGV-DF)*, Post-doctoral in Economics \hfill 2019

*Getulio Vargas Foundation (EESP/FGV-SP)*, Post-doctoral in Economics \hfill 2015

*University of Brasilia*, Doctor in Economics \hfill 2012

*University of Brasilia*, Master in Economics \hfill 2009

*Federal University of Rio Grande do Sul*, B.A. in Economics \hfill 2007\break

# Programming skills\hfill\break

*R, Python, Typescript, Stata, Matlab, PowerBI, LaTeX, Elisp, Shell, Machine Learning and IA*\hfill\break

# Grants and Fundings\hfill\break

Coordinator of Research Project financed by SEFAZ/RS \hfill 2023-2025

Colaborator of Research Project financed by SEFAZ/RS \hfill 2024-2025

Colaborator of Research Project financed by Fundação Itaú \hfill 2025-2026

Colaborator of Research Project financed by Secretaria de Economia/GO \hfill 2022-2025

FAPEG/IMB-GO Research Fellowship \hfill 2020-2021

CNPq Research Productivity Fellowship (*Grants no. 309726/2018-2 and 313725/2021-7*) \hfill 2019-2025

Programa Cátedras (ENAP) Fellowship \hfill 2020-2021

CNPq Post-Doctoral Fellowship (*Grant no. 153270/2018-7*) \hfill 2018-2019

PNPD/CAPES Post-Doctoral Fellowship \hfill 2014-2015

CAPES Doctoral Fellowship \hfill 2010-2012

CAPES Masters Fellowship \hfill 2008-2010\break

# Technical works\hfill\break

Research work for Secretaria da Fazenda do Rio Grande do Sul - *Desenvolvimento de Métodos de Análise de Efeitos de Alterações de Política Tributária*, 2025

Research work for Secretaria da Fazenda do Rio Grande do Sul - *Previsão de Receitas e Despesas para o Estado do Rio Grande do Sul*, 2025

Research work for Instituto Mauro Borges e Secretaria de Economia do Estado de
Goiás - *Previsão e determinantes do equilíbrio fiscal para o Estado de Goiás*, 2022.

Research work for Escola Nacional de Administração Pública (ENAP) - *Sinergias entre o programa microempreendedor individual e programas de assistência técnica*, 2020.

Research work for Febraban - *Serviços digitais, reservas compulsórias, política monetária e seus efeitos sobre as atividades bancárias*, 2020.

Member of the Economic Activity Working Group of the Data Science Committee for COVID-19 of the government of Rio Grande do Sul, 2020.

Member of the Committee for scientific initiation scholarships of Federal University of Pelotas (UFPel), 2015-2016.

Organizer of the XVII and XVIII Graduate Meeting of Federal University of Pelotas (UFPel), 2015-2016.

Organizer of the XXIV and XXV Scientific Initiation Congress of Federal University of Pelotas (UFPel), 2015-2016.

Research work for Febraban - *O Impacto da Lei de Falências no Mercado de Crédito Brasileiro*, 2015.

# Selected Publications\hfill\break

This list includes some selected recent publications. For the full list of my publications you can access my [Curriculum Lattes](http://lattes.cnpq.br/3708985718656687).\hfill\break

Ayub, Marcelo, Felipe G. Ribeiro, Regis A. Ely and Guilherme Stein. 2025. "[O impacto econômico do fim de um monopólio estatal: o caso do mercado de resseguros no Brasil](https://periodicos.fgv.br/rbe/article/view/92676)". *Revista Brasileira de Economia* 79: 1-24.

Lima, Gustavo L. R., Regis A. Ely and Daniel O. Cajueiro. 2024. "[Interactions between monetary and macroprudential policies](https://www.tandfonline.com/doi/full/10.1080/14697688.2024.2327065)". *Quantitative Finance* 24: 481-498.

Moscareli, Lúcio G., Mathias S. Tessmann, Lucas S. Beppler and Regis A. Ely. 2024. "[The effects of macroprudential policies in the Brazilian banking sector](https://www.emerald.com/insight/content/doi/10.1108/jfep-11-2023-0335/full/html)". *Journal of Financial Economic Policy* 17: 1.

Carvalho, Athos V. C., Douglas Silveira, Regis A. Ely and Daniel O. Cajueiro. 2023. "[A logarithmic market scoring rule agent-based model to evaluate prediction markets](https://link.springer.com/article/10.1007/s00191-023-00822-w)". *Journal of Evolutionary Economics* 33: 1303-1343.

Adão, Luiz F. S., Douglas Silveira, Regis A. Ely and Daniel O. Cajueiro.
Forthcoming. "[The impacts of interest rates on banks' loan porfolio
risk-taking](https://www.sciencedirect.com/science/article/abs/pii/S0165188922002251)". *Journal of Economics Dynamics and Control*, 2022.

Ely, Regis A., Benjamin M. Tabak and Anderson M. Teixeira. 2021. "[The
transmission mechanisms of macroprudential policies on bank
risk](https://www.sciencedirect.com/science/article/abs/pii/S0264999319313379)". *Economic Modelling* 94: 598-630.

Ely, Regis A., Rafael Parfitt, André Carraro and Felipe G. Ribeiro. 2019. "[Rural credit and the time allocation of agricultural households: the case of Pronaf in Brazil](https://onlinelibrary.wiley.com/doi/abs/10.1111/rode.12606)". *Review of Development Economics* 23(4): 1863-1890.

# Teaching\break

This list includes the current disciplines that I teach. For the full list of my teaching experience you can access my [Curriculum Lattes](http://lattes.cnpq.br/3708985718656687).\hfill\break

***Undergraduates***

Elementary Statistics \hfill 2013-present

Fundamentals of Finance \hfill 2013-present

***Graduates***

Statistics \hfill 2014-present

Macroeconomics \hfill 2013-present

Econometrics II \hfill 2016-present

Time series analysis \hfill 2014-present
